import Head from 'next/head'
import Navbar from '@/components/elements/Navbar/Navbar'
import Banner from '@/components/elements/Banner/Banner'
import Footer from '@/components/elements/Footer'
import About from '@/components/elements/About'
import Menu from '@/components/elements/Menu'

export default function Home() {
  return (
    <>
      <Head>
        <title>De Snelle Hap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Navbar/>
        <Banner/>
        <div className='bg-[#f0f0f0] shadow-inner'>
          <About/>
          <div className='border-t-2 w-3/4 mx-auto'></div>
          <Menu/>
        </div>
        <Footer/>
      </main>
    </>
  )
}
